specVersion: 0.2.0
name: home-polkadot-plo
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/home-subql.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot

dataSources:
  - kind: substrate/Runtime
    startBlock: 7667185
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
        - handler: handleMemoEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: MemoUpdated
