specVersion: 0.2.0
name: home-kusama-plo
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/home-subql.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: wss://kusama.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-kusama

dataSources:
  - kind: substrate/Runtime
    startBlock: 10840887
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloan

